### ISSUE TITLE
Bug "Check For Updates" (macOS)

### ISSUE THREAD

**Issue by sergiuwaxmann** [wise-coders/dbschema#71] opened 2022-05-26 18:05 UTC
## Description
When clicking _Help -> Software Updates -> Check For Updates_ in the Menu Bar on macOS, I get the following error:
`Application with ID 0607-8447-0273-3287 could not be found`.
Version: __DbSchema 9.0.1 build 220526__

## Exception Stacktrace:
```
java.io.IOException: Application with ID 0607-8447-0273-3287 could not be found
  at com.install4j.runtime.installer.helper.applaunch.ApplicationLauncherImpl.launchApplication(ApplicationLauncherImpl.java:82)
  at com.install4j.api.launcher.ApplicationLauncher.launchApplication(ApplicationLauncher.java:38)
  at com.wisecoders.dbs.sys.fx.FxCheckForUpdatesDialog$1.a(FxCheckForUpdatesDialog.java:50)
  at com.wisecoders.dbs.sys.fx.FxCheckForUpdatesDialog$1.call(FxCheckForUpdatesDialog.java:45)
  ...
```

## Screenshot
<img width="1508" alt="DbSchema error" src="https://user-images.githubusercontent.com/47978446/170548361-ef6aab8e-6e2b-49cc-aa08-4a200d221000.png">

**Comment by wise-coders** [comment] 2022-05-28 18:22
This issue will be fixed in the next minor release. It will be effective also after installing the new release.

**Closed by wise-coders** 2022-05-28 18:22 UTC

**Comment by wise-coders** [comment] 2022-06-24 10:00
9.0.2 is now released. Please check if the issue is fixed.

**Comment by sergiuwaxmann** [comment] 2022-06-24 10:13
@wise-coders The issue is fixed. Thank you!
