### ISSUE TITLE
Font size is too small

### ISSUE THREAD

**Issue by ansarizafar** [wise-coders/dbschema#24] opened 2020-04-04 07:59 UTC
I am using amazing dbschema version 8.2.9 build 200402. I wanted to know Is it possible to increase font size? For me font size is too small.

**Comment by wise-coders** [comment] 2020-04-06 06:29
Hello,

Please check the files in the DbSchema installation folder /config/appearance.
Is it about the diagram font size ? You can uncomment the custom.css and change it there.

If possible please send me a screenshot. I am wondering where in the application the font is small and if is any issue related to the monitor resolution.

Best regards,
 Dragos Pruteanu

--
 DbSchema - Wise Coders GbmH
82256 Fürstenfeldbruck bei München
 Email: support@dbschema.com - Web: [1] http://dbschema.com/

--

[1] http://www.example.com/

**Comment by barryrld** [comment] 2020-04-16 22:42
I can confirm that adding some CSS worked for me. For example, in my `/opt/dbschema/config/appearance/custom.css` file I added:

```
.root {
  -fx-font: 22px "SansSerif";
}

.diagram {
  font-family: monospace;
  font-size: 12px;
}
```

I'm on a 2x (200%) pixel density setting on my OS, so the above works nicely to boost the application font size up to a readable size. This does result is some slightly odd displays in some places, but nothing too serious. For example, the Database Settings Dialog looks like the attached screenshot.

![Screenshot from 2020-04-16 23-36-11](https://user-images.githubusercontent.com/1033560/79513349-86ba3f00-803b-11ea-8992-c763748c0fc9.png)

Also, the toolbar icons are still tiny. Does anyone know how we can boost the size of these? I'm guessing these may be pngs behind the scenes?

![Screenshot from 2020-04-16 23-41-55](https://user-images.githubusercontent.com/1033560/79513490-e0bb0480-803b-11ea-824a-e28afae120bc.png)

Hope this helps!

**Comment by wise-coders** [comment] 2020-04-21 18:40
Could you please test this version: 
https://dbschema.com/download-beta/DbSchema_macos_8_2_9.dmg
or
https://dbschema.com/download-beta/DbSchema_8_2_9.exe
Is still the same version number but a higher build number. We have upgraded JavaFx to the latest version, we think the issue is in JavaFx. A short feedback about this would be great.

**Comment by vincent-prz** [comment] 2020-05-12 12:44
I'm having a similar issue, with version 8.2.9. My main problem is that i am not able to read fonts on the SQL query editor, is there a css property I can change for this ?

Alternatively, is there a way to change the resolution on which Db Schema runs ?

Thank you.

**Comment by wise-coders** [comment] 2020-05-12 12:57
Please try to add

.code-editor {

font: 24px 'Monospaced';
}

to the same /opt/dbschema/config/appearance/custom.css

Could you please send one two screenshots for this ( not complete screen, just a part ) - one from the primary monitor and one from the second where it looks bad ? Please write also some details about the second monitor.

We intend to create an issue for JavaFx. The application should work fine on both monitors.

Best regards,
 Dragos Pruteanu

--
 DbSchema - Wise Coders GbmH
82256 Fürstenfeldbruck bei München
 Email: support@dbschema.com - Web: [1] http://dbschema.com/

--

[1] http://www.example.com/

**Comment by vincent-prz** [comment] 2020-05-12 13:23
Hello,

Thank you for your quick response. Here are some screenshots:

![Screenshot from 2020-05-12 15-17-41](https://user-images.githubusercontent.com/6080805/81696151-db4ab180-9463-11ea-8a71-92a90d381a96.png)


Here you can see that the fonts are too big for the container (because I increased the font size, see below).

![Screenshot from 2020-05-12 15-22-01](https://user-images.githubusercontent.com/6080805/81696560-59a75380-9464-11ea-8ae1-345682cc8348.png)


Here, after making the change you suggested, the SQL keyword are still display in a small font.

Here is my custom.css file:

```
.root {
-fx-font: 22px "SansSerif";
}
.diagram {
    font: 23px 'System';
    callout-font: 23px 'System';
}

.code-editor {
    font: 24px 'Monospaced';
}


```

Can you please advise ? Thanks!

**Comment by wise-coders** [comment] 2020-05-13 10:23
Hello,

First of all please install one of this versions:

[1] https://dbschema.com/download-beta/DbSchema_8_2_10.exe

[2] https://dbschema.com/download-beta/DbSchema_macos_8_2_10.dmg

We have a fix which may help regarding the font size, please let me know if the font is looking better by default.
If not please edit the custom.css file and uncomment this:

.code-editor {
  font: 2em 'Monospaced';
}

During our tests this works fine.
Please let me know if this did help.

Best regards,
 Dragos Pruteanu

--
 DbSchema - Wise Coders GbmH
82256 Fürstenfeldbruck bei München
 Email: support@dbschema.com - Web: [3] http://dbschema.com/

--

[1] https://dbschema.com/download/DbSchema_8_2_10.exe
[2] https://dbschema.com/download/DbSchema_macos_8_2_10.dmg
[3] http://www.example.com/

**Comment by dprutean** [comment] 2020-06-26 07:41
We have one more fix for this issue. In the Project / Appearance we added a button 'UI Scaling' where a tip about setting a parameter is shown. This will scale the complete application.

![image](https://user-images.githubusercontent.com/4970910/85832943-412f9600-b791-11ea-890c-5f6812b63396.png)

**Comment by TaIos** [comment] 2021-02-04 14:06
@dprutean this scaling helped me to set it right for my one main monitor (1920x1080) and my notebook (Thinkpad T14s). It would be very convenient for the user if this setting could be directly edited from the GUI interface of the application.

**Comment by dprutean** [comment] 2021-02-05 10:45
Thank you for writing about this. You are right, we will include this directly in the Appearance dialog. The next minor release will have it.

**Closed** 2023-01-18 07:57 UTC
