### ISSUE TITLE
not display button text

### ISSUE THREAD

**Issue by lien-dkseo** [wise-coders/dbschema#108] opened 2023-06-02 02:36 UTC
1. Please check DbSchema Help / Output logs for errors.

2. Please include the DbSchema version, operating system and used database
![image](https://github.com/wise-coders/dbschema/assets/91306431/db8c1692-4f27-43dc-8f69-555b76146191)

DbSchema 9.4.0 build 230525
Ubuntu 22.04.2 LTS

3. The steps to reproduce this issue

not display button text

![image](https://github.com/wise-coders/dbschema/assets/91306431/89c8b421-c01c-4aa4-93f0-1ea1eb960a12)
![image](https://github.com/wise-coders/dbschema/assets/91306431/5cb96668-45c1-42fb-95f3-861b65ce5265)

**Comment by wise-coders** [comment] 2023-06-03 05:24
Thank you for posting this. I tried to reproduce the issue, also under Ubuntu, and for me it is working fine.
I may assume the issue is related to JavaFX. Did you used the DbSchema.sh or another to install? (.zip, etc.)
Which Java version is showing in the Help / About dialog?

**Comment by wise-coders** [comment] 2023-10-06 06:09
Please check the current DbSchema 9.4.2. This issue should be fixed.

**Closed by wise-coders** 2023-10-06 06:09 UTC

**Comment by lien-dkseo** [comment] 2024-03-22 02:06
@wise-coders

sorry, i didn't say my ubuntu (22.04.4) language env. it is a Korean. (south korea)

same problem occurs in version 9.5.2.

thank you.

![image](https://github.com/wise-coders/dbschema/assets/91306431/80d01572-b8bf-43d2-adfe-eba9c09facfa)

![image](https://github.com/wise-coders/dbschema/assets/91306431/08ec6e7b-9822-4f05-b9e9-e766e24d76b8)

![image](https://github.com/wise-coders/dbschema/assets/91306431/8459e599-4719-44ac-ac48-56f69b03c7ef)

![image](https://github.com/wise-coders/dbschema/assets/91306431/a143a707-9bb8-4b89-8bae-9f8a9491f2f7)

**Comment by wise-coders** [comment] 2024-04-04 15:30
Please try first this beta update:
https://dbschema.com/beta.php
If the problem persists, please edit the file custom.css in the installation folder, and uncomment the font line. You can configure a different font. The problem is related to JavaFx default font.
